one_django_project/one_django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from one_django_project import views

urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# changing site name via attribute
# admin.AdminSite.site_header = 'My admin'

one_django_project/polls/urls.py
from django.urls import path
from polls import views

app_name = 'polls' # for namespace url
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/result/', views.result, name='result'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

one_django_project/rango/urls.py
from django.urls import path
from rango import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('category/<slug:category_name_slug>', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category')
]

one_django_project/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    '''
    Questions model
    '''
    question_text = models.CharField(max_length=128)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_fields = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    '''
    Choices model
    '''
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# Create your models here.

one_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
        
    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

one_django_project/rango/forms.py
# not needed separately, can be done with models.py

from django import forms

from rango.models import Category, Page

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text='Please enter the category name.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text='Please enter the page title.')
    url = forms.URLField(max_length=200, help_text='Please enter the page url.')
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        # or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')

one_django_project/one_django_project/views.py
from django.http import HttpResponse

def index(request):
    return HttpResponse('<h1>One Django Home</h1>\
    <ul>\
    <li><a href="/rango/">rango</a></li>\
    <li><a href="/polls/">polls</a></li>\
    </ul>')

one_django_project/polls/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse

from polls.models import Question, Choice

def index(request):
    latest_questions_list = Question.objects.order_by('-pub_date')[:5]
    context_dict = {}
    context_dict['latest_questions_list'] = latest_questions_list
    return render(request, 'polls/index.html', context=context_dict)

def detail(request, question_id):
    # try:
    #     question = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404("Question does not exist")
    question = get_object_or_404(Question, pk=question_id) # shortcut
    context_dict = {}
    context_dict['question'] = question
    return render(request, 'polls/detail.html', context=context_dict)

def result(request, question_id):
    response = f'You are looking at the results of the question {question_id}'
    return HttpResponse(response)

def vote(request, question_id):
    response = f'You are voting on question {question_id}'
    return HttpResponse(response)

one_django_project/rango/views.py
# Rango views
from django.shortcuts import render

from rango.models import Category, Page
from rango.forms import CategoryForm

def index(request):
    '''
    1. Query the database for list of all categories currently stored
    2. Order the categories in descending order by number of likes
    3. Retrieve only top 5 -- OR all if less than 5
    4. pass the list in the context_dict as template context that will be passed
    to the template engine
    '''

    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list
    return render(request, 'rango/index.html', context=context_dict)

def show_category(request, category_name_slug):
    '''
    Details page for a given category
    '''
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        pages = Page.objects.filter(category=category)
        context_dict['category'] = category
        context_dict['pages'] = pages
    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None
    return render(request, 'rango/category.html', context=context_dict)

def add_category(request):
    '''
    add category to database from the form
    '''
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
    return render(request, 'rango/add_category.html', {'form': form})


def about(request):
    '''
    Rango About page
    '''
    context_dict = {'authorname': 'Sameer Jain'}
    return render(request, 'rango/about.html', context=context_dict)

one_django_project/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Polls</title>
</head>
<body>
    <h1>Polls</h1>
    <div style="float: right">
        <a href="/">Django Home</a>
        <a href="/polls">Polls Home</a>
    </div>
    <div>
        {% if question %}
            <h2>Question Detail:</h2>
            {{ question.question_text }}
            <ul>
            
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}</li>
            {% endfor %}
                
            </ul>
        {% endif %}
    </div>
</body>
</html>

one_django_project/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Polls</title>
</head>
<body>
    <h1>Polls</h1>
    <div style="float: right">
        <a href="/">Django Home</a>
    </div>
    <div>
        <h2>Top 5 polls questions:</h2>
        {% if latest_questions_list %}
            <ul>
                
                {% for question in latest_questions_list %}
                    <!-- <li>
                        <a href="/polls/{{ question.id }}">{{ question.question_text }}</a>
                    </li> -->
                    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
                {% endfor %}
                    
            </ul>
        {% else %}
        <strong>No polls are available</strong>
        {% endif %}
            
    </div>
</body>
</html>

one_django_project/templates/rango/about.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <h1>Rango Says...</h1>
    <p>Here is the about page..</p>
    <div style="float: right">
            <a href="/rango">Rango Home</a>
            <a href="/">Django Home</a><br/>
    </div>
    <div>
            <label for="">Static Image of Rango</label>
            <img src="{% static "images/rango.jpeg" %}" alt="Picture of Rango">
        </div>
        <p>This tutorial has been put together by {{ authorname }}</p>
        <div>
            <label for="">Media Image of Cat</label>
            <img src="{{ MEDIA_URL }}images/cat.jpeg" alt="Picture of Cat">
        </div>
</body>
</html>

one_django_project/templates/rango/add_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Rango</title>
</head>
<body>
    <h1>Rango says</h1>
    <div style="float: right">
            <a href="/rango">Rango Home</a>
            <a href="/">Django Home</a><br/>
    </div>
    <h2>Add a Category</h2>
    <div>
        <form id="category_form" action="/rango/add_category/" method="post">
        {% csrf_token %}
        {% for field in form.hidden_fields %}
          {{ field }}
        {% endfor %}
        {% for field in form.visible_fields %}
          {{ field.errors }}
          {{ field.help_text }}
          {{ field }}
        {% endfor %}
        <input type="submit" name="submit" value="Create Category">
        </form>
    </div>
</body>
</html>

one_django_project/templates/rango/category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Rango</title>
</head>
<body>
    <div style="float: right">
            <a href="/rango">Rango Home</a>
            <a href="/rango/about">About</a>
            <a href="/">Django Home</a><br/>
    </div>
    <div>
    {% if category %}
        <h1>{{ category.name }}</h1>
        {% if pages %}
            <ul>   
            {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
        <strong>No pages currently in this category</strong>
        {% endif %}
    {% else %}
        <strong>The specified category does not exist!</strong>
    {% endif %}
    </div>
</body>
</html>

one_django_project/templates/rango/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Rango</title>
    </head>
    <body>
        <h1>Rango says</h1>
        <div style="float: right">
                <a href="/rango/about">About</a>
                <a href="/">Django Home</a><br/>
                <a href="/rango/add_category">Add New Category</a>
        </div>
        <div>
            hey there partner! <br/>
            <strong>{{ boldmessage }}</strong><br/>
        </div>
        <div>
            <h2>Most Liked Categories</h2>
            {% if categories %}
            <ul>
                {% for category in categories %}
                <li>
                    <a href="/rango/category/{{ category.slug }}">{{ category.name }}</a>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <strong>There are no categories present</strong>
            {% endif %}
        </div>
        <div>
            <h2>Most Viewed Pages</h2>
            {% if pages %}
            <ul>
                {% for page in pages %}
                <li><a href="{{ page.url }}">{{ page.title }} {{ page.views }}</a></li>
                {% endfor %}
            </ul>
            {% else %}
            <strong>There are no pages present</strong>
            {% endif %}
            </div>
        <div>
            <div>
                <label for="">Static Image of Rango</label>
                <img src="{% static 'images/rango.jpeg' %}" alt="Picture of Rango">
            </div>
            <div>
                <label for="">Media Image of Cat</label>
                <img src="{{ MEDIA_URL }}images/cat.jpeg" alt="Picture of Cat">
            </div>
        </div>
    </body>
</html>